apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-plotter-app
spec:
  selector:
    matchLabels:
      app: streamlit-plotter-app
  template:
    metadata:
      labels:
        app: streamlit-plotter-app
    spec:
      containers:
      - name: streamlit-plotter-app
        image: habert/streamlit-plotter:v1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8502

---

apiVersion: v1
kind: Service
metadata:
  name: argocd-svc
spec:
  selector:
    app: streamlit-plotter-app
  ports:
  - port: 80
    targetPort: 8502
